# Generated by Django 5.0 on 2024-01-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='change date')),
                ('origin_price', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='origin price')),
                ('tax', models.FloatField(default=0.06, verbose_name='tax value')),
                ('bank_commission', models.FloatField(default=0.02, verbose_name='bank commission')),
                ('shop_commission', models.FloatField(default=0.2, verbose_name='shop commission')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
            },
        ),
    ]
